# Generated by Django 3.1.7 on 2021-03-09 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golden',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to=settings.AUTH_USER_MODEL),
        ),
    ]
